{{ define "my.hpa" -}}
{{ $name:= .name }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ $name }}
  targetCPUUtilizationPercentage: 85

{{ end -}}

# Use range to define these hpas from the .Values.hpas array (~ for loop)
{{ range .Values.hpas }}
---
{{ template "my.hpa" . }}
{{ end -}}

